# Generated by Django 2.1.3 on 2018-11-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataX', models.IntegerField(max_length=11)),
                ('dataY', models.IntegerField(max_length=11)),
                ('dataZ', models.IntegerField(max_length=11)),
                ('dataRotateX', models.IntegerField(max_length=11)),
                ('dataRotateY', models.IntegerField(max_length=11)),
                ('dataRotateZ', models.IntegerField(max_length=11)),
                ('dataScale', models.IntegerField(max_length=11)),
                ('message', models.TextField()),
            ],
        ),
    ]
