# Generated by Django 2.1.3 on 2018-11-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181112_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='name',
            field=models.CharField(default='slide', max_length=250),
        ),
    ]
